In [1]:
import torch
flag = torch.cuda.is_available()
print(flag)

if flag:
    print(torch.cuda.get_device_name(0))
    print(torch.rand(3,3).cuda())

False


# Train Model

In [2]:
from train_data import start_train_data, save_train_data

train_num = 10
mcts_iter = 1000
train_data = start_train_data(train_num, mcts_iter, execution_mode='serial')
save_train_data(train_data, train_num, mcts_iter)

train_data[4]

TrainDataProcess(serial): 100%|██████████| 10/10 [00:05<00:00,  1.68it/s]


(array([[[ 0.,  0.,  1.,  0.],
         [ 0.,  0.,  1.,  0.],
         [ 0.,  0.,  1.,  0.],
         [ 0.,  0.,  1.,  0.],
         [ 0.,  0.,  1.,  0.]],
 
        [[-2.,  2.,  1.,  0.],
         [-1.,  1.,  1.,  0.],
         [ 1.,  1.,  1.,  0.],
         [ 2.,  2.,  1.,  0.],
         [ 0.,  2.,  1.,  0.]],
 
        [[ 1.,  3.,  1.,  0.],
         [ 0.,  2.,  1.,  0.],
         [-2.,  2.,  1.,  0.],
         [ 0.,  2.,  1.,  0.],
         [ 1.,  1.,  1.,  0.]],
 
        [[ 1.,  1.,  1.,  0.],
         [ 0.,  0.,  1.,  0.],
         [-1.,  1.,  1.,  0.],
         [ 0.,  0.,  1.,  0.],
         [ 0.,  0.,  1.,  0.]],
 
        [[ 0.,  0.,  1.,  0.],
         [ 0.,  0.,  1.,  0.],
         [ 0.,  0.,  1.,  0.],
         [ 0.,  0.,  1.,  0.],
         [ 0.,  0.,  1.,  0.]]]),
 array([0, 1]))

In [ ]:
from train_data import load_train_data


train_data_path = r"data\train_data\2025-11-20\MCTS1.0k_Games10.0k_Length133927(18-34).json"
train_data = load_train_data(train_data_path)
train_data[4]

(array([[[ 1.,  1.,  1.,  0.],
         [ 2.,  2.,  1.,  0.],
         [ 2.,  2.,  1.,  0.],
         [ 2.,  2.,  1.,  0.],
         [ 1.,  1.,  1.,  0.]],
 
        [[ 0.,  0.,  1.,  0.],
         [ 1.,  1.,  1.,  0.],
         [ 0.,  0.,  1.,  0.],
         [ 1.,  1.,  1.,  0.],
         [ 0.,  0.,  1.,  0.]],
 
        [[ 0.,  0.,  1.,  0.],
         [ 0.,  0.,  1.,  0.],
         [ 0.,  0.,  1.,  0.],
         [ 0.,  0.,  1.,  0.],
         [ 0.,  0.,  1.,  0.]],
 
        [[-2.,  2.,  1.,  0.],
         [-2.,  2.,  1.,  0.],
         [-2.,  2.,  1.,  0.],
         [-1.,  1.,  1.,  0.],
         [-1.,  1.,  1.,  0.]],
 
        [[-1.,  1.,  1.,  0.],
         [ 0.,  0.,  1.,  0.],
         [-1.,  1.,  1.,  0.],
         [ 0.,  0.,  1.,  0.],
         [ 0.,  0.,  1.,  0.]]]),
 (1, 0))

In [2]:
from train_model import ModelTrainer, get_model_info_dict, save_model_info_dict

trainer = ModelTrainer()
model_path, model = trainer.train_model(train_data, 10)

model_info_dict = get_model_info_dict(model_path, train_data_path, model)
save_model_info_dict(model_info_dict, "DeepLearningAI")

Epoch 1, Batch 100, Loss: 3.163
Epoch 1, Batch 200, Loss: 3.059
Epoch 1, Batch 300, Loss: 2.969
Epoch 1, Batch 400, Loss: 2.843
Epoch 1, Batch 500, Loss: 2.779
Epoch 1, Batch 600, Loss: 2.713
Epoch 1, Batch 700, Loss: 2.647
Epoch 1, Batch 800, Loss: 2.592
Epoch 1, Batch 900, Loss: 2.557
Epoch 1, Batch 1000, Loss: 2.507
Epoch 1, Batch 1100, Loss: 2.453
Epoch 1, Batch 1200, Loss: 2.394
Epoch 1, Batch 1300, Loss: 2.350
Epoch 1, Batch 1400, Loss: 2.336
Epoch 1, Batch 1500, Loss: 2.292
Epoch 1, Batch 1600, Loss: 2.178
Epoch 1, Batch 1700, Loss: 2.143
Epoch 1, Batch 1800, Loss: 2.138
Epoch 1, Batch 1900, Loss: 2.066
Epoch 1, Batch 2000, Loss: 2.071
Epoch 1, Batch 2100, Loss: 2.020
Epoch 1, Batch 2200, Loss: 1.943
Epoch 1, Batch 2300, Loss: 1.933
Epoch 1, Batch 2400, Loss: 1.883
Epoch 1, Batch 2500, Loss: 1.860
Epoch 1, Batch 2600, Loss: 1.859
Epoch 1, Batch 2700, Loss: 1.814
Epoch 1, Batch 2800, Loss: 1.741
Epoch 1, Batch 2900, Loss: 1.743
Epoch 1, Batch 3000, Loss: 1.755
Epoch 1, Batch 3100

Mcts Iter 30: 100%|██████████| 100/100 [00:02<00:00, 34.44it/s]


## Show the Result

In [ ]:
from celestialchess.ai.deeplearning import DeepLearningAI
from celestialchess import MCTSAI
from celestialchess.tools.evaluate_tool import get_model_score_by_mcts

chess_state = ((5,5), 2)

# policy_model = DeepLearningAI('models/dl_model(06-22-21-18)(136090)(32-64-128-256).pth')
model = DeepLearningAI(model_path)
get_model_score_by_mcts(model, chess_state)

Mcts Iter 10:   0%|          | 0/100 [00:00<?, ?it/s]

Mcts Iter 10: 100%|██████████| 100/100 [00:01<00:00, 86.01it/s]


(0, {'10': 0.41})

In [ ]:
model = DeepLearningAI(r"models\2024-06-28\dl_model(06-28-15-00)(136090).pth")

get_model_score_by_mcts(model, chess_state)

Mcts Iter 300: 100%|██████████| 100/100 [00:12<00:00,  8.30it/s]


(290,
 {'10': 0.815,
  '20': 0.76,
  '30': 0.73,
  '40': 0.655,
  '50': 0.725,
  '60': 0.685,
  '70': 0.63,
  '80': 0.63,
  '90': 0.57,
  '100': 0.51,
  '110': 0.565,
  '120': 0.59,
  '130': 0.59,
  '140': 0.52,
  '150': 0.595,
  '160': 0.56,
  '170': 0.61,
  '180': 0.54,
  '190': 0.5,
  '200': 0.54,
  '210': 0.58,
  '220': 0.6,
  '230': 0.54,
  '240': 0.58,
  '250': 0.56,
  '260': 0.535,
  '270': 0.585,
  '280': 0.56,
  '290': 0.575,
  '300': 0.52})

In [ ]:
from celestialchess.tools.evaluate_tool import get_best_c_param

chess_state = ((5,5), 2)
get_best_c_param(chess_state, 0.8)
# :XTvzUQcSJ6i2HS

100%|██████████| 11/11 [08:57<00:00, 48.88s/it]


(0.8,
 {'0.8 : 0.0': 604.5,
  '0.8 : 0.1': 559.5,
  '0.8 : 0.2': 504.0,
  '0.8 : 0.3': 520.5,
  '0.8 : 0.4': 534.0,
  '0.8 : 0.5': 537.5,
  '0.8 : 0.6': 530.0,
  '0.8 : 0.7': 509.5,
  '0.8 : 0.8': 513.5,
  '0.8 : 0.9': 520.5,
  '0.8 : 1.0': 532.0})

In [ ]:
from celestialchess import MCTSAI
from celestialchess.tools.evaluate_tool import get_model_score_by_mcts

chess_state = ((5,5), 2)
policy_model = DeepLearningAI(r"models\2024-06-28\dl_model(06-28-15-00)(136090).pth")
mcts_model = MCTSAI(100, c_param=0.5, policy_net=policy_model)

get_model_score_by_mcts(mcts_model, chess_state)

  0%|          | 0/999 [00:00<?, ?it/s]

  1%|          | 8/999 [26:49<55:23:30, 201.22s/it]

(80, {10: 0.735, 20: 0.69, 30: 0.67, 40: 0.565, 50: 0.545, 60: 0.56, 70: 0.555, 80: 0.5, 90: 0.49})


In [1]:
from celestialchess import MCTSAI
from celestialchess.tools.evaluate_tool import get_model_score_by_mcts

# 与其他AI算法进行对战
chess_state = ((5,5), 2)

mcts_ai = MCTSAI(100, c_param=0.8)
get_model_score_by_mcts(mcts_ai, chess_state)

Mcts Iter 10(process-5): 100%|██████████| 100/100 [00:04<00:00, 20.48it/s]


Win 80.5 / 100


Mcts Iter 20(process-5): 100%|██████████| 100/100 [00:04<00:00, 22.09it/s]


Win 66.0 / 100


Mcts Iter 30(process-5): 100%|██████████| 100/100 [00:04<00:00, 20.66it/s]


Win 66.5 / 100


Mcts Iter 40(process-5): 100%|██████████| 100/100 [00:04<00:00, 21.18it/s]


Win 66.0 / 100


Mcts Iter 50(process-5): 100%|██████████| 100/100 [00:05<00:00, 18.44it/s]


Win 58.5 / 100


Mcts Iter 60(process-5): 100%|██████████| 100/100 [00:05<00:00, 19.40it/s]


Win 62.0 / 100


Mcts Iter 70(process-5): 100%|██████████| 100/100 [00:05<00:00, 18.10it/s]


Win 60.5 / 100


Mcts Iter 80(process-5): 100%|██████████| 100/100 [00:05<00:00, 19.78it/s]


Win 54.5 / 100


Mcts Iter 90(process-5): 100%|██████████| 100/100 [00:05<00:00, 19.96it/s]


Win 51.5 / 100


Mcts Iter 100(process-5): 100%|██████████| 100/100 [00:04<00:00, 20.70it/s]


Win 51.5 / 100


Mcts Iter 110(process-5): 100%|██████████| 100/100 [00:04<00:00, 20.74it/s]


Win 48.5 / 100


Mcts Iter 120(process-5): 100%|██████████| 100/100 [00:04<00:00, 21.09it/s]

Win 44.0 / 100


(110,
 {'10': 0.805,
  '20': 0.66,
  '30': 0.665,
  '40': 0.66,
  '50': 0.585,
  '60': 0.62,
  '70': 0.605,
  '80': 0.545,
  '90': 0.515,
  '100': 0.515,
  '110': 0.485,
  '120': 0.44})

In [2]:
from celestialchess import MinimaxAI
from celestialchess.tools.evaluate_tool import get_model_score_by_mcts

chess_state = ((5,5), 2)
minimax_ai = MinimaxAI(6)
# minimax_ai.set_transposition_mode(chess_state, r"Q:\Project\Celestial-Chess\transposition_table")

print(get_model_score_by_mcts(minimax_ai, chess_state))

Mcts Iter 10(process-5): 100%|██████████| 100/100 [00:04<00:00, 24.73it/s]

Win 0 / 100
(0, {'10': 0.0})
